[2024-05-14T03:39:34.211+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T03:39:34.267+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TAREAS_EN_PARALELO_Y_EN_SERIE.second_task manual__2024-05-14T03:39:29.168944+00:00 [queued]>
[2024-05-14T03:39:34.298+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TAREAS_EN_PARALELO_Y_EN_SERIE.second_task manual__2024-05-14T03:39:29.168944+00:00 [queued]>
[2024-05-14T03:39:34.305+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 5
[2024-05-14T03:39:34.349+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): second_task> on 2024-05-14 03:39:29.168944+00:00
[2024-05-14T03:39:34.365+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=64) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-14T03:39:34.376+0000] {standard_task_runner.py:63} INFO - Started process 68 to run task
[2024-05-14T03:39:34.368+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'TAREAS_EN_PARALELO_Y_EN_SERIE', 'second_task', 'manual__2024-05-14T03:39:29.168944+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/paralelo_serie_dag.py', '--cfg-path', '/tmp/tmpzvbu7yh6']
[2024-05-14T03:39:34.381+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask second_task
[2024-05-14T03:39:34.510+0000] {task_command.py:426} INFO - Running <TaskInstance: TAREAS_EN_PARALELO_Y_EN_SERIE.second_task manual__2024-05-14T03:39:29.168944+00:00 [running]> on host 33978f229c7f
[2024-05-14T03:39:34.681+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='TAREAS_EN_PARALELO_Y_EN_SERIE' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T03:39:29.168944+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-14T03:39:29.168944+00:00'
[2024-05-14T03:39:34.724+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T03:39:34.758+0000] {logging_mixin.py:188} INFO - Ejecutando second_task
[2024-05-14T03:39:34.762+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-14T03:39:34.764+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T03:39:34.786+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=TAREAS_EN_PARALELO_Y_EN_SERIE, task_id=second_task, execution_date=20240514T033929, start_date=20240514T033934, end_date=20240514T033934
[2024-05-14T03:39:34.832+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-14T03:39:34.877+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-14T03:39:34.879+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
