[2024-05-14T03:39:37.730+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T03:39:37.772+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TAREAS_EN_PARALELO_Y_EN_SERIE.third_task manual__2024-05-14T03:39:29.168944+00:00 [queued]>
[2024-05-14T03:39:37.789+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TAREAS_EN_PARALELO_Y_EN_SERIE.third_task manual__2024-05-14T03:39:29.168944+00:00 [queued]>
[2024-05-14T03:39:37.790+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 5
[2024-05-14T03:39:37.806+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): third_task> on 2024-05-14 03:39:29.168944+00:00
[2024-05-14T03:39:37.811+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-14T03:39:37.812+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2024-05-14T03:39:37.813+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'TAREAS_EN_PARALELO_Y_EN_SERIE', 'third_task', 'manual__2024-05-14T03:39:29.168944+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/paralelo_serie_dag.py', '--cfg-path', '/tmp/tmprn6o0904']
[2024-05-14T03:39:37.817+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask third_task
[2024-05-14T03:39:37.876+0000] {task_command.py:426} INFO - Running <TaskInstance: TAREAS_EN_PARALELO_Y_EN_SERIE.third_task manual__2024-05-14T03:39:29.168944+00:00 [running]> on host 33978f229c7f
[2024-05-14T03:39:37.989+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='TAREAS_EN_PARALELO_Y_EN_SERIE' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T03:39:29.168944+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-14T03:39:29.168944+00:00'
[2024-05-14T03:39:37.993+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T03:39:37.994+0000] {logging_mixin.py:188} INFO - Ejecutando third_task
[2024-05-14T03:39:37.995+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-14T03:39:37.996+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T03:39:38.009+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=TAREAS_EN_PARALELO_Y_EN_SERIE, task_id=third_task, execution_date=20240514T033929, start_date=20240514T033937, end_date=20240514T033938
[2024-05-14T03:39:38.069+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-14T03:39:38.101+0000] {taskinstance.py:3482} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-05-14T03:39:38.111+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
